### ISSUE TITLE
How to download llama3 weight

### ISSUE THREAD

**Issue by lsnls** [ddw2AIGROUP2CQUPT/PA-LLaVA#3]
Hello, authors!

Thanks for your wonderful work! I need to download the `meta-llama/Meta-Llama-3-8B-Instruct` weights before running inference on my dataset using the `PA-LLaVA` model. However, my access request for `meta-llama/Meta-Llama-3-8B-Instruct` was rejected, likely because I'm from China. Could you please advise me on how to download the LLaMA 3 weights?

I look forward to your reply and assistance! Thank you!

Best regards,
Suoni

**Comment by ddw2AIGROUP2CQUPT** [comment]
Thank you for your interest. You just need to complete the application on HuggingFace.

**Comment by lsnls** [comment]
Unfortunately, my application on llama3 was rejected.
