### ISSUE TITLE
the data format about test

### ISSUE THREAD

**Issue by lsnls** [ddw2AIGROUP2CQUPT/PA-LLaVA#4]
Hi, Authors,

Thank you for your valuable work! Could you please clarify the data format used when running inference?

Best regards,
Suoni

**Comment by ddw2AIGROUP2CQUPT** [comment]
Thank you for your interest. You can modify the 'EvalDataset' code to fit your data format. Just make sure that the 'question' field contains your designed questions and the 'img' field corresponds to the respective images.

**Comment by lsnls** [comment]
I got it, Thank you so much for your help!
